version: '3'

services:

  db:
    image: postgres:13.10
    environment:
      - POSTGRES_PASSWORD=SWAD123zxc
      - POSTGRES_USER=django_user
      - POSTGRES_DB=django_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - foodgram_net
    restart: always

  backend:
    image: fedodor/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    networks:
      - foodgram_net
    depends_on:
      - db
    restart: always

  frontend:
    image: fedodor/foodgram_frontend:latest
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    networks:
      - foodgram_net
    depends_on:
      - db
    restart: always

  nginx:
    image: fedodor/foodgram_nginx
    env_file: .env
    networks:
      - foodgram_net
    ports:
      - 7000:80
    volumes:
    #  - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ../frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media: