version: '3'

services:

  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    ports:
      - 5432
    restart: always

  backend:
    image: fedodor/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: fedodor/foodgram_frontend:latest
    env_file: .env
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - db
    restart: on-failure

  nginx:
    image: fedodor/foodgram_nginx
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/media/
    depends_on:
      - db
      - backend
      - frontend
    restart: always

volumes:
  pg_data_production:
  static_volume:
  media_volume: