version: '3'
services:

  db:
    image: postgres:13:10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/frontend_static
      - ./frontend/:/app/result_build/

  backend:
    build: ./backend/
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/recipes/image/
    env_file:
      - .env

  nginx:
    build: ./infra/
    restart: always
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/media/recipes/image/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static_volume:
  media_volume:
