version: '3.3'
services:

  db:
    container_name: db
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build: ./infra/
    restart: always
    ports:
      - 7000:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data_production:
  static_volume:
  media_volume:
