version: '3'

services:

  db:
    container_name: foodgram_db
    image: postgres:14
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    restart: always

  backend:
    container_name: foodgram_backend
    image: fedodor/foodgram_backend:latest
    env_file: ../.env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    container_name: foodgram_frontend
    image: fedodor/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    restart: on-failure

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
      - 7000:80
    volumes:
      - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - db
      - backend
      - frontend
    restart: always

volumes:
  pg_data_production:
  static_volume:
  media_volume: