version: '3.3'
services:

  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: foodgram_backend
    build: ../backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ../.env

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static:
  media:
  postgres_data:
