version: '3'

services:

  db:
    container_name: foodgram_db
    image: postgres:13.0-alpine
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    restart: always

  backend:
    container_name: foodgram_backend
    image: fedodor/foodgram_backend:latest
    env_file: ../.env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    container_name: foodgram_frontend
    image: fedodor/foodgram_frontend:latest
    volumes:
      - static_volume:/frontend_static/app/build/
    restart: on-failure

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
      - 7000:80
    volumes:
      - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/var/html/media/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data_production:
  static_volume:
  media_volume: