# Generated by Django 3.2.16 on 2024-03-25 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='following_relationships', through='users.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
