# Generated by Django 3.2.16 on 2024-03-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('subscriber',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscriber',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='author',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_to', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscribed_to'), name='unique_subscribed_to'),
        ),
    ]
