# Generated by Django 3.2.16 on 2024-03-06 12:49

import api.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z'), django.contrib.auth.validators.UnicodeUsernameValidator(), api.validators.validate_username], verbose_name='Псевдоним'),
        ),
    ]
